// tslint:disable
/**
 * Select API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelectedOption
 */
export interface SelectedOption  {
    /**
     * 
     * @type {string}
     * @memberof SelectedOption
     */
    value: string;
}

export function SelectedOptionFromJSON(json: any): SelectedOption {
    return {
        'value': json['value'],
    };
}

export function SelectedOptionToJSON(value?: SelectedOption): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'value': value.value,
    };
}


