// tslint:disable
/**
 * Select API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerMessage
 */
export interface ServerMessage  {
    /**
     * 
     * @type {string}
     * @memberof ServerMessage
     */
    message?: string;
}

export function ServerMessageFromJSON(json: any): ServerMessage {
    return {
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ServerMessageToJSON(value?: ServerMessage): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'message': value.message,
    };
}


